'''Тут слова на которые реагирует бот, что 
обращение было к нему. Его имя и команда могут быть сказаны
в любой последовательности и даже в перемешку и тд...,
главное без продолжительной паузы'''

TRIGGERS = {'эмбер'}


data_set = {
    # команды для работы с погодой:
    'проверь погоду': 'get_city',
    'покажи погоду': 'get_city',
    'какая погода в городе': 'get_city',
    'какая температура сейчас': 'get_city',
    'какая погода на улице': 'get_city',
    'что по температуре': 'get_city',
    'температура сейчас': 'get_city',
    'погода сейчас': 'get_city',
    'температура в городе': 'get_city',
    'какая сегодня погода': 'get_city',
    
    # команды для работы со стимом: ПОРАБОТАТЬ С ЭТИМ БЛОКОМ КОМАНД!
    'начни игру в вальхейм': 'open_valheim',
    'запуск вальхейма': 'open_valheim',
    'играть в вальхейм': 'open_valheim',
    'начать вальхейм': 'open_valheim',
    'вальхейм запуск': 'open_valheim',
    'открой игру вальхейм': 'open_valheim',
    'начать игру вальхейм': 'open_valheim',
    'открыть вальхейм': 'open_valheim',
    'загрузить вальхейм': 'open_valheim',
    'загрузи вальхейм': 'open_valheim',
    'запустить стим': 'open_steam',
    'начать стим': 'open_steam',
    'открыть платформу стим': 'open_steam',
    'стим открой': 'open_steam',
    'запуск площадки стим': 'open_steam',
    'стим загрузи': 'open_steam',
    'загрузить стим': 'open_steam',
    'начать платформу стим': 'open_steam',
    'стим начни': 'open_steam',
    'начать работу со стимом': 'open_steam',
    
    # команды для работы с ПК:
    'закрыть компьютер': 'offPc',
    'завершить работу компьютера': 'offPc',
    'компьютер выключить': 'offPc',
    'завершить компьютер': 'offPc',
    'отключить ПК': 'offPc',
    'закончить работу на ПК': 'offPc',
    'закрыть ПК': 'offPc',
    'выключить ПК': 'offPc',
    'выключение компьютера': 'offPc',
    'завершение работы ПК': 'offPc',
    # 'включи компьютер': 'onPc включаю пк сэр',
    
    #команды для работы с ботом:
    'заверши работу': 'offBot',
    'выключись': 'offBot',
    'отключись': 'offBot',
    'до новых встреч': 'offBot',
    'уходи': 'offBot',
    'остановись': 'offBot',
    'заверши': 'offBot',
    'отключить': 'offBot',
    'прощай': 'offBot',
    'выход': 'offBot',
    
    # болтовня с помощником
    'привет, как дела': 'passive здравствуйте, сэр. Я в порядке, а вы?',
    'что ты умеешь': 'passive сэр вот список того, что я умею делать: открывать браузер, узнавать погоду, открыть игру вальхейм, запустить стим, пообщаться с вами',
    'ты тут': 'passive да сэр',
    'поможешь мне': 'passive всегда к вашим услугам сэр',
    
    # команды для работы со звуком:
    'сделай тише': 'mute_volume',
    'выключи звуковое сопровождение': 'mute_volume',
    'отключи звук': 'mute_volume',
    'звук выключи': 'mute_volume',
    'без звука': 'mute_volume',
    'звук отключи': 'mute_volume',
    'уровень звука минимум': 'mute_volume',
    'звук на ноль': 'mute_volume',
    'громкость на ноль': 'mute_volume',
    'тишина': 'mute_volume',
    'установи громкость': 'set_volume',
    'измени уровень громкости': 'set_volume',
    'установи уровень звука': 'set_volume',
    'увеличь уровень звука': 'set_volume',
    'понизь уровень звука': 'set_volume',
    'громкость вверх': 'set_volume',
    'громкость вниз': 'set_volume',
    'громкость на максимум': 'set_volume',
    'громкость на минимум': 'set_volume',
    'установи звук': 'set_volume',
    
    
    # команды для работы с корзиной:
    'очистить корзину': 'clear_trash',
    'удалить все из корзины': 'clear_trash',
    'корзина пуста': 'clear_trash',
    'удалить корзину': 'clear_trash',
    'очисти мусор': 'clear_trash',
    'пустая корзина': 'clear_trash',
    'очистка мусора': 'clear_trash',
    'очистить мусор': 'clear_trash',
    'удали все из корзины': 'clear_trash',
    'корзина очистить': 'clear_trash',
    
    # команды для работы с диспетчером задач:
    'открыть диспетчер': 'task_manager',
    'начать диспетчер задач': 'task_manager',
    'запустить диспетчер задач': 'task_manager',
    'запустить диспетчер': 'task_manager',
    'открыть управление задачами': 'task_manager',
    'запустить управление задачами': 'task_manager',
    'начать управление задачами': 'task_manager',
    'открыть менеджер задач': 'task_manager',
    'начать менеджер задач': 'task_manager',
    'запустить менеджер задач': 'task_manager',
    
    # команды для работы с окнами:
    'все окна вниз': 'windows_down',
    'окна вниз': 'windows_down',
    'свернуть окна': 'windows_down',
    'свернуть все': 'windows_down',
    'вниз все окна': 'windows_down',
    'вниз окна': 'windows_down',
    'окна свернуть': 'windows_down',
    'все свернуть': 'windows_down',
    'все окна свернуть': 'windows_down',
    'окна все свернуть': 'windows_down',
    'развернуть все окна': 'windows_up',
    'разверни все': 'windows_up',
    'все окна вверх': 'windows_up',
    'все окна развернуть': 'windows_up',
    'окна вверх': 'windows_up',
    'показать все окна': 'windows_up',
    'все окна показать': 'windows_up',
    'окна развернуть': 'windows_up',
    'все окна на экран': 'windows_up',
    'все окна открыть': 'windows_up',
    'переключить окно': 'swap_windows',
    'поменять местами окна': 'swap_windows',
    'сменить окно': 'swap_windows',
    'смена окон': 'swap_windows',
    'переключение между окнами': 'swap_windows',
    'переключись на другое окно': 'swap_windows',
    'переключение окон': 'swap_windows',
    'переключись на следующее окно': 'swap_windows',
    'перейти к другому окну': 'swap_windows',
    'сменить активное окно': 'swap_windows',
    'закрыть активное окно': 'close_current_window',
    'закрыть текущее': 'close_current_window',
    'закрыть это окно': 'close_current_window',
    'закрой это': 'close_current_window',
    'удалить текущее окно': 'close_current_window',
    'закрыть выбранное окно': 'close_current_window',
    'удалить это окно': 'close_current_window',
    'закрыть': 'close_current_window',
    'закрой выбранное окно': 'close_current_window',
    'закрыть окно': 'close_current_window',
    
    # команды для работы со скриншотами:
    'сделай скрин': 'screenshot',
    'захват экрана': 'screenshot',
    'скриншот экрана': 'screenshot',
    'сделай захват экрана': 'screenshot',
    'скрин экрана': 'screenshot',
    'сделай фото экрана': 'screenshot',
    'фото экрана': 'screenshot',
    'захвати экран': 'screenshot',
    'скриншот': 'screenshot',
    'сделай снимок': 'screenshot',
    
    # команды для работы со спящим режимом и блокировкой пк:
    # спящий режим пк
    'включи спящий режим': 'sleep_mode',
    'активировать спящий режим': 'sleep_mode',
    'режим сна': 'sleep_mode',
    'перевести в спящий режим': 'sleep_mode',
    'войти в спящий режим': 'sleep_mode',
    'включить спящий режим': 'sleep_mode',
    'заснуть': 'sleep_mode',
    'выключить в спящий режим': 'sleep_mode',
    'перейти в спящий режим': 'sleep_mode',
    'включить режим сна': 'sleep_mode',
    #блокировка пк
    'включить блокировку': 'lock_mode',
    'активировать режим блокировки': 'lock_mode',
    'блокировка': 'lock_mode',
    'включи режим блокировки': 'lock_mode',
    'заблокируй': 'lock_mode',
    'включить режим безопасности': 'lock_mode',
    'активировать безопасный режим': 'lock_mode',
    'заблокировать компьютер': 'lock_mode',
    'включить блокировку ПК': 'lock_mode',
    'закрыть ПК': 'lock_mode',
    
    # команды для работы со сменой языка:
    'переключить язык': 'swap_language',
    'сменить раскладку клавиатуры': 'swap_language',
    'переключи на другой язык': 'swap_language',
    'поменяй язык': 'swap_language',
    'переключи язык': 'swap_language',
    'сменить язык': 'swap_language',
    'переключи на русский язык': 'swap_language',
    'переключи на английский язык': 'swap_language',
    'поменяй раскладку на английскую': 'swap_language',
    'поменяй раскладку на русскую': 'swap_language',
    
    # команды для работы с буфером обмена:
    'покажи буфер обмена': 'clipboard',
    'что в буфере обмена': 'clipboard',
    'открой буфер': 'clipboard',
    'показать буфер обмена': 'clipboard',
    'открыть буфер': 'clipboard',
    'буфер': 'clipboard',
    'просмотреть буфер обмена': 'clipboard',
    'посмотреть буфер обмена': 'clipboard',
    'показать буфер': 'clipboard',
    'открыть содержимое буфера обмена': 'clipboard',
    # 'режим со звуком': 'mute_volume звук активирован, сэр',
    # 'звук на минимум': 'set_volume_min да, сэр',
    # 'минимальный уровень громкости': 'set_volume_min да, сэр',
    # 'звук на двадцать пять': 'set_volume_min да, сэр',
    # 'громкость на середину': 'set_volume_half да, сэр',
    # 'средний уровень громкости': 'set_volume_half да, сэр',
    # 'звук пятьдесят': 'set_volume_half выполняю, сэр',
    # 'звук на максимум':'set_volume_max сделано, сэр',
    # 'полный уровень громкости': 'set_volume_max сделано, сэр',
    # 'звук на сто': 'set_volume_max сделано, сэр',
    
    'добавь задачу': 'add_to_backlog',
    'запиши заметку': 'add_to_backlog',
    'новая задача': 'add_to_backlog',
    'добавь в список задач': 'add_to_backlog',
    'запиши новую задачу': 'add_to_backlog',
    'создай задачу': 'add_to_backlog',
    'добавь в бэклог': 'add_to_backlog',
    'создай заметку': 'add_to_backlog',
    'новая заметка': 'add_to_backlog',
    'добавить в бэклог': 'add_to_backlog',
        
    # команды для работ со временем:
    'скажи время': 'tell_time',
    'какой сейчас час': 'tell_time',
    'сколько время': 'tell_time',
    'текущее время': 'tell_time',
    'что по времени': 'tell_time',
    'который час': 'tell_time',
    'сколько сейчас времени': 'tell_time',
    'время': 'tell_time',
    'час': 'tell_time',
    'какое сейчас время': 'tell_time',
    # таймер
    'завести таймер': 'start_timer',
    'поставить таймер': 'start_timer',
    'таймер начать': 'start_timer',
    'таймер включить': 'start_timer',
    'запуск таймера': 'start_timer',
    'включить таймер': 'start_timer',
    'активировать таймер': 'start_timer',
    'начать отсчёт': 'start_timer',
    'начни таймер': 'start_timer',
    'пуск таймера': 'start_timer',
    'поставить таймер на паузу': 'pause_timer',
    'приостановить таймер': 'pause_timer',
    'остановить таймер': 'pause_timer',
    'таймер пауза': 'pause_timer',
    'таймер остановиться': 'pause_timer',
    'таймер остановись': 'pause_timer',
    'остановка таймера': 'pause_timer',
    'таймер стоп': 'pause_timer',
    'заморозить таймер': 'pause_timer',
    'пауза таймера': 'pause_timer',
    'продолжить таймер': 'resume_timer',
    'возобновить таймер': 'resume_timer',
    'таймер продолжить': 'resume_timer',
    'продолжи таймер': 'resume_timer',
    'возобнови отсчет': 'resume_timer',
    'продолжить отсчет': 'resume_timer',
    'продолжение таймера': 'resume_timer',
    'возобновление таймера': 'resume_timer',
    'продолжи отсчет времени': 'resume_timer',
    'возобнови таймер': 'resume_timer',
    'остановить таймер': 'stop_timer',
    'стоп таймер': 'stop_timer',
    'закончить таймер': 'stop_timer',
    'завершить таймер': 'stop_timer',
    'таймер стоп': 'stop_timer',
    'отменить таймер': 'stop_timer',
    'убрать таймер': 'stop_timer',
    'остановка таймера': 'stop_timer',
    'таймер остановить': 'stop_timer',
    'таймер завершить': 'stop_timer',
    # секундомер
    'начать секундомер': 'start_stopwatch',
    'запустить секундомер': 'start_stopwatch',
    'секундомер старт': 'start_stopwatch',
    'секундомер включить': 'start_stopwatch',
    'включить секундомер': 'start_stopwatch',
    'секундомер начать': 'start_stopwatch',
    'старт секундомера': 'start_stopwatch',
    'начни секундомер': 'start_stopwatch',
    'пуск секундомера': 'start_stopwatch',
    'завести секундомер': 'start_stopwatch',
    'секундомер на паузу': 'pause_stopwatch',
    'приостановить секундомер': 'pause_stopwatch',
    'остановить секундомер': 'pause_stopwatch',
    'секундомер пауза': 'pause_stopwatch',
    'секундомер остановиться': 'pause_stopwatch',
    'секундомер остановись': 'pause_stopwatch',
    'остановка секундомера': 'pause_stopwatch',
    'секундомер стоп': 'pause_stopwatch',
    'заморозить секундомер': 'pause_stopwatch',
    'пауза секундомера': 'pause_stopwatch',
    'возобнови секундомер': 'resume_stopwatch',
    'продолжить секундомер': 'resume_stopwatch',
    'секундомер продолжить': 'resume_stopwatch',
    'продолжи секундомер': 'resume_stopwatch',
    'возобнови отсчет секундомера': 'resume_stopwatch',
    'продолжить отсчет секундомера': 'resume_stopwatch',
    'продолжение секундомера': 'resume_stopwatch',
    'возобновление секундомера': 'resume_stopwatch',
    'продолжи отсчет секундомера': 'resume_stopwatch',
    'возобнови секундомер': 'resume_stopwatch',
    'остановить секундомер': 'stop_stopwatch',
    'стоп секундомер': 'stop_stopwatch',
    'закончить секундомер': 'stop_stopwatch',
    'завершить секундомер': 'stop_stopwatch',
    'секундомер стоп': 'stop_stopwatch',
    'отменить секундомер': 'stop_stopwatch',
    'убрать секундомер': 'stop_stopwatch',
    'остановка секундомера': 'stop_stopwatch',
    'секундомер остановить': 'stop_stopwatch',
    'секундомер завершить': 'stop_stopwatch',
    
    # команды для работы с гугл картами:
    'найди на карте': 'map_search',
    'покажи на карте': 'map_search',
    'где на карте': 'map_search',
    'открой на карте': 'map_search',
    'место на карте': 'map_search',
    'расположение на карте': 'map_search',
    'отобрази на карте': 'map_search',
    'карта места': 'map_search',
    'карта расположения': 'map_search',
    'указать на карте': 'map_search',
    
    # команды для работы с youtube:
    'перейти на ютуб': 'youtube',
    'начать ютуб': 'youtube',
    'загрузить ютуб': 'youtube',
    'открой ютуб': 'youtube',
    'посмотреть ютуб': 'youtube',
    'запустить видео на ютубе': 'youtube',
    'открой новую вкладку на ютуб': 'youtube',
    'начать просмотр на ютубе': 'youtube',
    'включить ютуб': 'youtube',
    'запусти вкладку ютуб': 'youtube',
    
    'найди на ютубе': 'youtube_search',
    'поищи видео': 'youtube_search',
    'открой на ютубе': 'youtube_search',
    'найди мне видео': 'youtube_search',
    'покажи на ютубе': 'youtube_search',
    'ищи на ютуб': 'youtube_search',
    'отыщи на ютубе': 'youtube_search',
    'хочу видео': 'youtube_search',
    'проиграй на ютубе': 'youtube_search',
    'поиск на ютубе': 'youtube_search',
    
    "открой видео": "open_video",
    "покажи видео": "open_video",
    "запусти первое видео": "open_video",
    "начни воспроизведение": "open_video",
    "хочу посмотреть": "open_video",
    "включи клип": "open_video",
    "дай мне видео": "open_video",
    "включи видео": "open_video",
    "проиграй ролик": "open_video",
    "пуск видео": "open_video",
    #ставим паузу
    "пауза": "pause_video",
    "поставь видео на паузу": "pause_video",
    "поставь на паузу ролик": "pause_video",
    "видео на паузу": "pause_video",
    "ролик на паузу": "pause_video",
    "приостановить видео": "pause_video",
    "приостановить": "pause_video",
    "пауза видео": "pause_video",
    "временно пауза": "pause_video",
    "поставь видос на паузу": "pause_video",
    #снимаем с паузы
    "продолжить воспроизведение": "play_video",
    "снять с паузы": "play_video",
    "продолжить видео": "play_video",
    "продолжить ролик": "play_video",
    "возобновить воспроизведение": "play_video",
    "продолжай": "play_video",
    "продолжить": "play_video",
    "снять видео с паузы": "play_video",
    "снять ролик с паузы": "play_video",
    "возобновить": "play_video",
    #перемотка видео на любой процент от 10 до 90%
    "перемотай видео": "jump_to_percent",
    "измени позицию в видео": "jump_to_percent",
    "перейди к другому моменту": "jump_to_percent",
    "измени процент просмотра": "jump_to_percent",
    "перемести видеоплеер": "jump_to_percent",
    "смени позицию воспроизведения": "jump_to_percent",
    "переключи место воспроизведения": "jump_to_percent",
    "переход в видео": "jump_to_percent",
    "перемещение по видео": "jump_to_percent",
    "изменение момента просмотра": "jump_to_percent",
    #перемотка видео на 5 секунд вперед/назад
    "отмотай на пять секунд назад": "rewind_5_seconds_back",
    "назад на пять секунд": "rewind_5_seconds_back",
    "перемотай пять секунды назад": "rewind_5_seconds_back",
    "откати на пять секунд": "rewind_5_seconds_back",
    "верни на пять секунд назад": "rewind_5_seconds_back",
    "пять секунд назад": "rewind_5_seconds_back",
    "перемести на пять секунд назад": "rewind_5_seconds_back",
    "переходи на пять секунд назад": "rewind_5_seconds_back",
    "вернуться на пять секунд": "rewind_5_seconds_back",
    "откатить на пять секунд назад": "rewind_5_seconds_back",
    
    "перемотай на пять секунд вперёд": "rewind_5_seconds_forward",
    "вперёд на пять секунд": "rewind_5_seconds_forward",
    "отмотай пять секунды вперёд": "rewind_5_seconds_forward",
    "переходи на пять секунд вперёд": "rewind_5_seconds_forward",
    "пять секунд вперёд": "rewind_5_seconds_forward",
    "перенести на пять секунд вперёд": "rewind_5_seconds_forward",
    "перейти на пять секунд вперёд": "rewind_5_seconds_forward",
    "продолжить на пять секунд вперёд": "rewind_5_seconds_forward",
    "переключить на пять секунд вперёд": "rewind_5_seconds_forward",
    "откатить на пять секунд вперёд": "rewind_5_seconds_forward",
    #перемотка видео на 10 секунд вперед/назад
    "отмотай на десять секунд назад": "rewind_10_seconds_back",
    "назад на десять секунд": "rewind_10_seconds_back",
    "перемотай десять секунды назад": "rewind_10_seconds_back",
    "откати на десять секунд": "rewind_10_seconds_back",
    "верни на десять секунд назад": "rewind_10_seconds_back",
    "десять секунд назад": "rewind_10_seconds_back",
    "перемести на десять секунд назад": "rewind_10_seconds_back",
    "переходи на десять секунд назад": "rewind_10_seconds_back",
    "вернуться на десять секунд": "rewind_10_seconds_back",
    "откатить на десять секунд назад": "rewind_10_seconds_back",
    
    "перемотай на десять секунд вперёд": "rewind_10_seconds_forward",
    "вперёд на десять секунд": "rewind_10_seconds_forward",
    "отмотай десять секунды вперёд": "rewind_10_seconds_forward",
    "переходи на десять секунд вперёд": "rewind_10_seconds_forward",
    "десять секунд вперёд": "rewind_10_seconds_forward",
    "перенести на десять секунд вперёд": "rewind_10_seconds_forward",
    "пройти десять секунд вперёд": "rewind_10_seconds_forward",
    "продолжить на десять секунд вперёд": "rewind_10_seconds_forward",
    "переключить на десять секунд вперёд": "rewind_10_seconds_forward",
    "откатить на десять секунд вперёд": "rewind_10_seconds_forward",
    
    #предыдущий/следующий кадр:
    "предыдущий кадр": "previous_frame",
    "перейти к предыдущему кадру": "previous_frame",
    "перемотай к предыдущему кадру": "previous_frame",
    "верни кадр назад": "previous_frame",
    "покажи предыдущий кадр": "previous_frame",
    "возврат к предыдущему кадру": "previous_frame",
    "откатиться на кадр назад": "previous_frame",
    "назад на один кадр": "previous_frame",
    "к предыдущему кадру": "previous_frame",
    "вернуться к предыдущему кадру": "previous_frame",
    
    "следующий кадр": "next_frame",
    "перейти к следующему кадру": "next_frame",
    "перемотай к следующему кадру": "next_frame",
    "продвинься на кадр вперед": "next_frame",
    "покажи следующий кадр": "next_frame",
    "вперед на один кадр": "next_frame",
    "продолжить к следующему кадру": "next_frame",
    "к следующему кадру": "next_frame",
    "переключиться на следующий кадр": "next_frame",
    "пройти к следующему кадру": "next_frame",
    
    #предыдущее/следующее видео:
    "предыдущее видео": "shift_p_previous_video",
    "перейти к предыдущему видео": "shift_p_previous_video",
    "перемотай к предыдущему клипу": "shift_p_previous_video",
    "верни на предыдущий клип": "shift_p_previous_video",
    "вернуться к предыдущему видео": "shift_p_previous_video",
    "показать предыдущее видео": "shift_p_previous_video",
    "откатиться к предыдущему видео": "shift_p_previous_video",
    "назад к предыдущему видео": "shift_p_previous_video",
    "переключить на предыдущее видео": "shift_p_previous_video",
    "перейти на предыдущий клип": "shift_p_previous_video",
    
    "следующее видео": "shift_n_next_video",
    "перейти к следующему видео": "shift_n_next_video",
    "перемотай к следующему клипу": "shift_n_next_video",
    "пройти к следующему клипу": "shift_n_next_video",
    "показать следующее видео": "shift_n_next_video",
    "продолжить к следующему видео": "shift_n_next_video",
    "вперед к следующему видео": "shift_n_next_video",
    "переключить на следующее видео": "shift_n_next_video",
    "перейти на следующий клип": "shift_n_next_video",
    "продвинься к следующему видео": "shift_n_next_video",
    
    #уменьшить/увеличить скорость воспроизведения видео:
    "уменьшить скорость": "decrease_playback_speed",
    "замедлить воспроизведение": "decrease_playback_speed",
    "сделай медленнее": "decrease_playback_speed",
    "уменьшить темп": "decrease_playback_speed",
    "понизь скорость показа": "decrease_playback_speed",
    "замедлить показ": "decrease_playback_speed",
    "меньше скорость": "decrease_playback_speed",
    "сбросить скорость": "decrease_playback_speed",
    "уменьшить скорость проигрывания": "decrease_playback_speed",
    "понизить темп воспроизведения": "decrease_playback_speed",
    
    "увеличить скорость": "increase_playback_speed",
    "ускорить воспроизведение": "increase_playback_speed",
    "сделай быстрее": "increase_playback_speed",
    "увеличить темп": "increase_playback_speed",
    "подними скорость показа": "increase_playback_speed",
    "ускорить показ": "increase_playback_speed",
    "больше скорость": "increase_playback_speed",
    "добавить скорость": "increase_playback_speed",
    "увеличить скорость проигрывания": "increase_playback_speed",
    "повысить темп воспроизведения": "increase_playback_speed",
    
    #включить/выключить субтитры:
    "включи субтитры": "subtitles_on",
    "включить субтитры": "subtitles_on",
    "покажи субтитры": "subtitles_on",
    "включи текст": "subtitles_on",
    "включить текст": "subtitles_on",
    "покажи текст": "subtitles_on",
    "включи титры": "subtitles_on",
    "включить титры": "subtitles_on",
    "покажи титры": "subtitles_on",
    "покажи перевод": "subtitles_on",
    
    "выключи субтитры": "subtitles_off",
    "выключить субтитры": "subtitles_off",
    "убери субтитры": "subtitles_off",
    "выключи текст": "subtitles_off",
    "выключить текст": "subtitles_off",
    "убери текст": "subtitles_off",
    "выключи титры": "subtitles_off",
    "выключить титры": "subtitles_off",
    "убери титры": "subtitles_off",
    "убери перевод": "subtitles_off",
    
    #увеличить/уменьшить шрифт:
    "увеличь размер шрифта": "change_font_size_plus",
    "увеличить размер шрифта": "change_font_size_plus",
    "увеличь шрифт": "change_font_size_plus",
    "увеличить шрифт": "change_font_size_plus",
    "увеличь текст": "change_font_size_plus",
    "увеличить текст": "change_font_size_plus",
    "увеличь размер текста": "change_font_size_plus",
    "увеличить размер текста": "change_font_size_plus",
    "увеличь размер букв": "change_font_size_plus",
    "увеличить размер букв": "change_font_size_plus",
    
    "уменьши размер шрифта": "change_font_size_minus",
    "уменьшить размер шрифта": "change_font_size_minus",
    "уменьши шрифт": "change_font_size_minus",
    "уменьшить шрифт": "change_font_size_minus",
    "уменьши текст": "change_font_size_minus",
    "уменьшить текст": "change_font_size_minus",
    "уменьши размер текста": "change_font_size_minus",
    "уменьшить размер текста": "change_font_size_minus",
    "уменьши размер букв": "change_font_size_minus",
    "уменьшить размер букв": "change_font_size_minus",
    
    #открыть/закрыть полноэкранный режим:
    "включи полноэкранный режим": "fullscreen_on",
    "включить полноэкранный режим": "fullscreen_on",
    "включи полный экран": "fullscreen_on",
    "включить полный экран": "fullscreen_on",
    "включи полный режим": "fullscreen_on",
    "включить полный режим": "fullscreen_on",
    "включи режим полного экрана": "fullscreen_on",
    "включить режим полного экрана": "fullscreen_on",
    "включи режим полного режима": "fullscreen_on",
    "включить режим полного режима": "fullscreen_on",
    
    "выключи полноэкранный режим": "fullscreen_off",
    "выключить полноэкранный режим": "fullscreen_off",
    "выключи полный экран": "fullscreen_off",
    "выключить полный экран": "fullscreen_off",
    "выключи полный режим": "fullscreen_off",
    "выключить полный режим": "fullscreen_off",
    "выключи режим полного экрана": "fullscreen_off",
    "выключить режим полного экрана": "fullscreen_off",
    "выключи режим полного режима": "fullscreen_off",
    "выключить режим полного режима": "fullscreen_off",
    
    #включить/выключить мини-проигрыватель:
    "включить мини-проигрыватель": "mini_player_on",
    "переключить на мини-режим": "mini_player_on",
    "хочу мини-плеер": "mini_player_on",
    "выключить мини-проигрыватель": "mini_player_on",
    "закрыть мини-плеер": "mini_player_on",
    "обычный режим плеера": "mini_player_on",
    "не нужен мини-плеер": "mini_player_on",
    "убери мини-режим": "mini_player_on",
    "переключись на маленький экран": "mini_player_on",
    "верни стандартный плеер": "mini_player_on",
    
    "выключить мини-проигрыватель": "mini_player_off",
    "переключить на мини-режим": "mini_player_off",
    "хочу мини-плеер": "mini_player_off",
    "выключить мини-проигрыватель": "mini_player_off",
    "закрыть мини-плеер": "mini_player_off",
    "обычный режим плеера": "mini_player_off",
    "не нужен мини-плеер": "mini_player_off",
    "убери мини-режим": "mini_player_off",
    "переключись на маленький экран": "mini_player_off",
    "верни стандартный плеер": "mini_player_off",
    
    #включить/выключить звук:
    "включи звук": "mute_on",
    "включить звук": "mute_on",
    "включи звучание": "mute_on",
    "включить звучание": "mute_on",
    "включи аудио": "mute_on",
    "включить аудио": "mute_on",
    "включи звуковой сигнал": "mute_on",
    "включить звуковой сигнал": "mute_on",
    "включи звуковое воспроизведение": "mute_on",
    "включить звуковое воспроизведение": "mute_on",
    
    "выключи звук": "mute_off",
    "выключить звук": "mute_off",
    "выключи звучание": "mute_off",
    "выключить звучание": "mute_off",
    "выключи аудио": "mute_off",
    "выключить аудио": "mute_off",
    "выключи звуковой сигнал": "mute_off",
    "выключить звуковой сигнал": "mute_off",
    "выключи звуковое воспроизведение": "mute_off",
    "выключить звуковое воспроизведение": "mute_off",
    
    #увеличить/уменьшить мини-плеер:
    "увеличь окно проигрывателя": "resize_player_window_increase",
    "увеличить окно проигрывателя": "resize_player_window_increase",
    "увеличь размер окна проигрывателя": "resize_player_window_increase",
    "увеличить размер окна проигрывателя": "resize_player_window_increase",
    "увеличь размер плеера": "resize_player_window_increase",
    "увеличить размер плеера": "resize_player_window_increase",
    "увеличь окно воспроизведения": "resize_player_window_increase",
    "увеличить окно воспроизведения": "resize_player_window_increase",
    "увеличь размер окна воспроизведения": "resize_player_window_increase",
    "увеличить размер окна воспроизведения": "resize_player_window_increase",
    
    "уменьши окно проигрывателя": "resize_player_window_decrease",
    "уменьшить окно проигрывателя": "resize_player_window_decrease",
    "уменьши размер окна проигрывателя": "resize_player_window_decrease",
    "уменьшить размер окна проигрывателя": "resize_player_window_decrease",
    "уменьши размер плеера": "resize_player_window_decrease",
    "уменьшить размер плеера": "resize_player_window_decrease",
    "уменьши окно воспроизведения": "resize_player_window_decrease",
    "уменьшить окно воспроизведения": "resize_player_window_decrease",
    "уменьши размер окна воспроизведения": "resize_player_window_decrease",
    "уменьшить размер окна воспроизведения": "resize_player_window_decrease",
    
    #увеличить уменьшить громкость:
    "увеличь громкость": "adjust_volume_increase",
    "увеличить громкость": "adjust_volume_increase",
    "увеличь звук": "adjust_volume_increase",
    "увеличить звук": "adjust_volume_increase",
    "подними громкость": "adjust_volume_increase",
    "поднять громкость": "adjust_volume_increase",
    "подними звук": "adjust_volume_increase",
    "поднять звук": "adjust_volume_increase",
    "увеличь звук на 5%": "adjust_volume_increase",
    "увеличить звук на 5%": "adjust_volume_increase",
    
    "уменьши громкость": "adjust_volume_decrease",
    "уменьшить громкость": "adjust_volume_decrease",
    "уменьши звук": "adjust_volume_decrease",
    "уменьшить звук": "adjust_volume_decrease",
    "понизь громкость": "adjust_volume_decrease",
    "понизить громкость": "adjust_volume_decrease",
    "понизь звук": "adjust_volume_decrease",
    "понизить звук": "adjust_volume_decrease",
    "уменьши звук на 5%": "adjust_volume_decrease",
    "уменьшить звук на 5%": "adjust_volume_decrease",
    
    #приблизить/отдалить изображение:
    "приблизь": "zoom_in",
    "приблизить": "zoom_in",
    "увеличь": "zoom_in",
    "увеличить": "zoom_in",
    "приблизь изображение": "zoom_in",
    "приблизить изображение": "zoom_in",
    "приблизь видео": "zoom_in",
    "приблизить видео": "zoom_in",
    "увеличь изображение": "zoom_in",
    "увеличить изображение": "zoom_in",
    
    "отдалить": "zoom_out",
    "уменьши": "zoom_out",
    "уменьшить": "zoom_out",
    "отдалить изображение": "zoom_out",
    "уменьши изображение": "zoom_out",
    "отдалить видео": "zoom_out",
    "уменьши видео": "zoom_out",
    "отдалить видеопоток": "zoom_out",
    "уменьши видеопоток": "zoom_out",
    "отдаление": "zoom_out",
    
    #закрыть плеер:
    "закрыть плеер": "close_player_or_dialog",
    "убери окно": "close_player_or_dialog",
    "закрыть текущее окно": "close_player_or_dialog",
    "заверши просмотр": "close_player_or_dialog",
    "закрыть диалог": "close_player_or_dialog",
    "убери диалоговое окно": "close_player_or_dialog",
    "закончить сессию": "close_player_or_dialog",
    "выход": "close_player_or_dialog",
    "прекрати показ": "close_player_or_dialog",
    "окончание просмотра": "close_player_or_dialog",
    
    #передвинуть плеер вверх/вниз вправо/влево:
    "перемести вверх": "move_up",
    "переместить вверх": "move_up",
    "поднимись": "move_up",
    "подняться": "move_up",
    "вверх": "move_up",
    "перемести вверх на одну ячейку": "move_up",
    "переместить вверх на одну ячейку": "move_up",
    "поднимись на одну ячейку": "move_up",
    "подняться на одну ячейку": "move_up",
    "перемести вверх на одну позицию": "move_up",
    
    "перемести влево": "move_left",
    "переместить влево": "move_left",
    "передвинь влево": "move_left",
    "передвинуть влево": "move_left",
    "влево": "move_left",
    "перемести влево на одну ячейку": "move_left",
    "переместить влево на одну ячейку": "move_left",
    "передвинь влево на одну ячейку": "move_left",
    "передвинуть влево на одну ячейку": "move_left",
    "перемести влево на одну позицию": "move_left",
    
    "перемести вниз": "move_down",
    "переместить вниз": "move_down",
    "опусти вниз": "move_down",
    "опустить вниз": "move_down",
    "вниз": "move_down",
    "перемести вниз на одну ячейку": "move_down",
    "переместить вниз на одну ячейку": "move_down",
    "опусти вниз на одну ячейку": "move_down",
    "опустить вниз на одну ячейку": "move_down",
    "перемести вниз на одну позицию": "move_down",
    
    "перемести вправо": "move_right",
    "переместить вправо": "move_right",
    "передвинь вправо": "move_right",
    "передвинуть вправо": "move_right",
    "вправо": "move_right",
    "перемести вправо на одну ячейку": "move_right",
    "переместить вправо на одну ячейку": "move_right",
    "передвинь вправо на одну ячейку": "move_right",
    "передвинуть вправо на одну ячейку": "move_right",
    "перемести вправо на одну позицию": "move_right",
    
    #команды для работы с google:
    'запусти интернет': 'browser',
    'открой интернет': 'browser',
    'пройти в интернет': 'browser',
    'загрузи браузер': 'browser',
    'загрузи интернет': 'browser',
    'начать работу в интернете': 'browser',
    'запустить браузер': 'browser',
    'начать браузер': 'browser',
    'перейти в браузер': 'browser',
    'открыть браузер': 'browser',
    
    'найди в интернете': 'web_search',
    'поищи в сети': 'web_search',
    'открой в браузере': 'web_search',
    'найди мне в интернете': 'web_search',
    'покажи в браузере': 'web_search',
    'ищи в интернете': 'web_search',
    'отыщи в сети': 'web_search',
    'хочу узнать': 'web_search',
    'что говорит интернет': 'web_search',
    'поиск в интернете': 'web_search',
    
    # Команды для создания папки
    "создай папку": "create_folder",
    "хочу новую папку": "create_folder",
    "сделай папку": "create_folder",
    "новая папка": "create_folder",
    "папка, пожалуйста": "create_folder",
    "добавь папку": "create_folder",
    "прошу папку": "create_folder",
    "хочу папку": "create_folder",
    "мне нужна папка": "create_folder",
    "заведи папку": "create_folder",

    # Команды для создания Excel файла
    "создай эксель файл": "create_excel_file",
    "новый эксель документ": "create_excel_file",
    "хочу эксель файл": "create_excel_file",
    "сделай эксель файл": "create_excel_file",
    "новый файл эксель": "create_excel_file",
    "эксель, пожалуйста": "create_excel_file",
    "добавь эксель файл": "create_excel_file",
    "хочу эксель документ": "create_excel_file",
    "мне нужен эксель": "create_excel_file",
    "заведи эксель файл": "create_excel_file",

    # Команды для создания Word файла
    "создай ворд файл": "create_word_file",
    "новый ворд документ": "create_word_file",
    "хочу ворд файл": "create_word_file",
    "сделай ворд файл": "create_word_file",
    "новый файл ворд": "create_word_file",
    "ворд, пожалуйста": "create_word_file",
    "добавь ворд файл": "create_word_file",
    "хочу ворд документ": "create_word_file",
    "мне нужен ворд": "create_word_file",
    "заведи ворд файл": "create_word_file",

    # Команды для создания PowerPoint файла
    "создай ппт файл": "create_ppt_file",
    "новая презентация": "create_ppt_file",
    "хочу ппт файл": "create_ppt_file",
    "сделай презентацию": "create_ppt_file",
    "новый файл ппт": "create_ppt_file",
    "ппт, пожалуйста": "create_ppt_file",
    "добавь ппт файл": "create_ppt_file",
    "хочу ппт документ": "create_ppt_file",
    "мне нужен ппт": "create_ppt_file",
    "заведи ппт файл": "create_ppt_file",

    # Команды для создания TXT файла
    "создай текстовый файл": "create_txt_file",
    "новый текстовый документ": "create_txt_file",
    "хочу текстовый файл": "create_txt_file",
    "сделай текстовый файл": "create_txt_file",
    "новый файл текстовый": "create_txt_file",
    "текстовый, пожалуйста": "create_txt_file",
    "добавь текстовый файл": "create_txt_file",
    "хочу текстовый документ": "create_txt_file",
    "мне нужен текстовый": "create_txt_file",
    "заведи текстовый файл": "create_txt_file",
    
    # Команды для будильника:
    # установить будильник:
    "установить будильник": "alarm",
    "задать время пробуждения": "alarm",
    "хочу проснуться в": "alarm",
    "включить будильник на": "alarm",
    "поставить будильник": "alarm",
    "завести будильник": "alarm",
    "пробудить меня в": "alarm",
    "будильник на": "alarm",
    "разбудить в": "alarm",
    "установи будильник на": "alarm",

    # остановить будильник:
    "остановить будильник": "stop_alarm",
    "выключить будильник": "stop_alarm",
    "отключить звук будильника": "stop_alarm",
    "хватит будить": "stop_alarm",
    "перестань будить": "stop_alarm",
    "отключи будильник": "stop_alarm",
    "останови звук": "stop_alarm",
    "закончить будильник": "stop_alarm",
    "прекрати будильник": "stop_alarm",
    "выруби будильник": "stop_alarm",

    # прервать будильник:
    "отменить будильник": "cancel_alarm",
    "удалить будильник": "cancel_alarm",
    "отключить установленный будильник": "cancel_alarm",
    "забыть про будильник": "cancel_alarm",
    "не будить меня": "cancel_alarm",
    "отмена будильника": "cancel_alarm",
    "удоли будильник": "cancel_alarm",
    "не нужен будильник": "cancel_alarm",
    "отключи установку будильника": "cancel_alarm",
    "будильник не нужен": "cancel_alarm",
    
}